### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by blkerby**
I needed to do a pass through all the projects to fix the lava-rising FX in Climb; this previously didn't exist in the randomizer so I think it never got tested, but it is planned to be used in the randomizer in v114 (and already is on dev). There were two main problems:

1) It was using escape flashing "paletteflags" (0x1F). I removed these across all the themes (including Base), consistent with what we did for the Tourian Escape Rooms. In many themes, this flashing was inapplicable to their palette so it looked bad, and in any case we don't want it to have escape flashing (only during the escape sequence, where this room state won't be used anyway).

2) It had the wavy heat BG effect even though there is no heat. Again I removed this across all the themes, similar to what we did with Gauntlet, etc.

Along the way I fixed a bunch of other small issues (described in the individual commit messages). I don't think any of these will be controversial. Most of them are straightforward fixes of errors, but there are a few that could use a closer review:

- Yellow Maridia theme: The background in Tourian First Room had a discontinuity that was visible. It looks like it was drawn assuming a 100% scroll Y rate, but then the actual scroll rate was 75%. I think the 75% scroll is probably good so I tried to solve it by completing the background so it wouldn't have that discontinuity. But you may be able to improve what I did.
- Wrecked Ship theme: There was a similar issue with the background in Green Brinstar Main Shaft. Again I tried to solve it by creating more of a transition between the two background patterns.
- Outer Crateria theme: Big Boy Room had its vanilla tiling, as I guess we missed/skipped it. So I took a pass at tiling it. There's a bit of air space between the enemy corpses and the ceiling, which I didn't know how to solve, but it looks like that's a thing in other themes too so maybe we just accept it?

### CODE REVIEW

**Comment by amoebaOfDoom** [comment]
The bg on the Torian elevator doesn't line up with the doors correctly unless it's 100%.

**Comment by amoebaOfDoom** [comment]
The WS green brinstar shaft just has the wrong BG on the top two rows.

**Comment by amoebaOfDoom** [comment]
In other cases, we left the mismatched wavy bg on the base rooms for when players are playing with vanilla tiling. Are you sure you want to remove the wavy bg from the normally unused state from the base?

**Comment by amoebaOfDoom** [comment]
Tourian elevator for outer Crateria also got missed.

**Comment by amoebaOfDoom** [comment]
I left the wavy bg alone but changes the other things I mentioned.

**Comment by blkerby** [comment]
> The WS green brinstar shaft just has the wrong BG on the top two rows.

Yeah that was my first thought too, then I tried changing the top two rows to make them the same as the others, and it ended up with just a solid color showing up in the background of the elevator ride which maybe didn't look great. So I assumed it may have been intentional to put something different there. But I'm fine with whatever

**Comment by blkerby** [comment]
> In other cases, we left the mismatched wavy bg on the base rooms for when players are playing with vanilla tiling. Are you sure you want to remove the wavy bg from the normally unused state from the base?

Yeah, I was thinking about that. For Gauntlet and Crateria Power Bomb Room, players would generally be familiar with how these rooms look so the heat effect wouldn't be likely to create confusion, so it made sense to keep them unchanged when using vanilla theming. The lava rising state is a little different in that it's unlikely for players to observe it in the vanilla game, and we are already changing its vanilla appearance by removing the palette flashing (as we also do for the other escape rooms), so removing the wavy BG seemed to me like maybe the better choice to avoid creating confusion where players might think it's heated. But I don't have strong feelings about it either way.

**Comment by amoebaOfDoom** [comment]
> > The WS green brinstar shaft just has the wrong BG on the top two rows.
> 
> Yeah that was my first thought too, then I tried changing the top two rows to make them the same as the others, and it ended up with just a solid color showing up in the background of the elevator ride which maybe didn't look great. So I assumed it may have been intentional to put something different there. But I'm fine with whatever

Hmm, I didn't really notice that effect, but I can soften the transition. However, the other version had just as sharp of an edge.

**Pull request merged**
